In [4]:
import spacy
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("data/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [16]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [17]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [24]:
X_train.shape

(4457,)

In [25]:
type(X_train)

pandas.core.series.Series

In [26]:
X_train[:10]

4788                         Ü thk of wat to eat tonight.
827                           Hahaha..use your brain dear
2905    HI DARLIN I HOPE YOU HAD A NICE NIGHT I WISH I...
1530    Should I have picked up a receipt or something...
1560    Single line with a big meaning::::: "Miss anyt...
5074    Gud ni8 dear..slp well..take care..swt dreams....
408     Hello! Good week? Fancy a drink or something l...
2856    Your gonna be the death if me. I'm gonna leave...
1740                   U guys never invite me anywhere :(
1682                                               Y lei?
Name: Message, dtype: object

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7741 sparse matrix of type '<class 'numpy.int64'>'
	with 59523 stored elements in Compressed Sparse Row format>

In [31]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
X_train_cv.shape

(4457, 7741)

In [33]:
v.get_feature_names_out().shape

(7741,)

In [36]:
X_train_np = X_train_cv.toarray()
X_train_np

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
np.where(X_train_np[0] != 0)

(array([2531, 4899, 6851, 6931, 6965, 7402]),)

In [49]:
X_train[:4]

4788                         Ü thk of wat to eat tonight.
827                           Hahaha..use your brain dear
2905    HI DARLIN I HOPE YOU HAD A NICE NIGHT I WISH I...
1530    Should I have picked up a receipt or something...
Name: Message, dtype: object

In [50]:
X_train_np[0][1771]

0

In [51]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [53]:
X_test_cv = v.transform(X_test)

In [55]:
from sklearn.metrics import classification_report
y_preds=model.predict(X_test_cv)
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       969
           1       0.95      0.93      0.94       146

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [57]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [60]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [61]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [63]:
print(classification_report(y_test,clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       969
           1       0.95      0.93      0.94       146

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

